package nets.suncaper.bootdemo.domain;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ID
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.NAME
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.BRANCH
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    private String branch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.PERCENTAGE
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    private Integer percentage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.PHONE
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    private Integer phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.EMAIL
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.FIRST_NAME
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    private String firstName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ID
     *
     * @return the value of student.ID
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ID
     *
     * @param id the value for student.ID
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.NAME
     *
     * @return the value of student.NAME
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.NAME
     *
     * @param name the value for student.NAME
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.BRANCH
     *
     * @return the value of student.BRANCH
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.BRANCH
     *
     * @param branch the value for student.BRANCH
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.PERCENTAGE
     *
     * @return the value of student.PERCENTAGE
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public Integer getPercentage() {
        return percentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.PERCENTAGE
     *
     * @param percentage the value for student.PERCENTAGE
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public void setPercentage(Integer percentage) {
        this.percentage = percentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.PHONE
     *
     * @return the value of student.PHONE
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.PHONE
     *
     * @param phone the value for student.PHONE
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.EMAIL
     *
     * @return the value of student.EMAIL
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.EMAIL
     *
     * @param email the value for student.EMAIL
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.FIRST_NAME
     *
     * @return the value of student.FIRST_NAME
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.FIRST_NAME
     *
     * @param firstName the value for student.FIRST_NAME
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Student other = (Student) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getBranch() == null ? other.getBranch() == null : this.getBranch().equals(other.getBranch()))
            && (this.getPercentage() == null ? other.getPercentage() == null : this.getPercentage().equals(other.getPercentage()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getFirstName() == null ? other.getFirstName() == null : this.getFirstName().equals(other.getFirstName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sun May 17 17:25:23 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getBranch() == null) ? 0 : getBranch().hashCode());
        result = prime * result + ((getPercentage() == null) ? 0 : getPercentage().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getFirstName() == null) ? 0 : getFirstName().hashCode());
        return result;
    }
}